
[[commands]]
== Commands

This section describes the bindings to API functions that enqueue commands in <<queue, command queues>> 
for execution on devices.

Unless otherwise specified, the following facts apply to any enqueue_xxx(&nbsp;) function described in this section:

[[enqueue_params]]

[unstyled]
- - the *_blocking_* parameter is a boolean indicating if the call must block until the
command has been executed (_true_), or return immediately after the command has been enqueued (_false_);
- - the *{_we_}* parameter ('wait events') is an optional list of <<event, _events_>> on which to wait
for before command execution;
- - the *_ge_* parameter ('generate event') is an optional boolean indicating if the function must
generate and return an <<event, _event_>> identifying the command (_ge_=_true_), or if it
must not (_ge_=_false_ or _nil_, in which case the returned _event_ is _nil_);
- - the *_{integer}[3]_* notation denotes an array of up to 3 integers
(missing entries default to 0, e.g. _{5}_ is equivalent to _{5, 0, 0}_); 
- - the *_ptr_* parameter or return value is a 
http://www.lua.org/manual/5.3/manual.html#lua_pushlightuserdata[lightuserdata] encapsulating
a valid pointer (_void*_) to memory;
- - the semantics and optionality of functions' parameters are the same as for the
corresponding parameters of the underlying _clEnqueueXxxx(&nbsp;)_ functions.


=== buffer commands

[[enqueue_read_buffer]]
* _event_ = *enqueue_read_buffer*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _blocking_>>, _offset_, _size_, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueReadBuffer.html[clEnqueueReadBuffer].#

[[enqueue_write_buffer]]
* _event_ = *enqueue_write_buffer*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _blocking_>>, _offset_, _size_, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueWriteBuffer.html[clEnqueueWriteBuffer].#

[[enqueue_copy_buffer]]
* _event_ = *enqueue_copy_buffer*(<<queue, _queue_>>, <<buffer, _srcbuffer_>>, <<buffer, _dstbuffer_>>, _srcoffset_, _dstoffset_, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueCopyBuffer.html[clEnqueueCopyBuffer].#

[[enqueue_fill_buffer]]
* _event_ = *enqueue_fill_buffer*(<<queue, _queue_>>, <<buffer, _buffer_>>, _pattern_, _offset_, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_pattern_: binary string +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueFillBuffer.html[clEnqueueFillBuffer].#

'''

[[enqueue_read_buffer_rect]]
* _event_ = *enqueue_read_buffer_rect*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _blocking_>>, _..._, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#arg4-6: _buffer_origin_, _host_origin_, _region_ : <<enqueue_params, {integer}[3]>>, +
arg7-8: _bufferrowpitch_, _bufferslicepitch_: integer, +
arg9-10: _hostrowpitch_, _hostslicepitch_: integer, +
arg11: <<enqueue_params, _ptr_>>: lightuserdata. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueReadBufferRect.html[clEnqueueReadBufferRect].#

[[enqueue_write_buffer_rect]]
* _event_ = *enqueue_write_buffer_rect*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _blocking_>>, _..._, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#arg4-6: _bufferorigin_, _hostorigin_, _region_: <<enqueue_params, {integer}[3]>>, +
arg7-8: _bufferrowpitch_, _bufferslicepitch_: integer, +
arg9-10: _hostrowpitch_, _hostslicepitch_: integer, +
arg11: <<enqueue_params, _ptr_>>: lightuserdata. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueWriteBufferRect.html[clEnqueueWriteBufferRect].#

[[enqueue_copy_buffer_rect]]
* _event_ = *enqueue_copy_buffer_rect*(<<queue, _queue_>>, <<buffer, _srcbuffer_>>, <<buffer, _dstbuffer_>>, _..._, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#arg4-6: _srcorigin_, _dstorigin_, _region_ : <<enqueue_params, {integer}[3]>>, +
arg7-8: _srcrowpitch_, _srcslicepitch_: integer. +
arg9-10: _dstrowpitch_, _dstslicepitch_: integer. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueCopyBufferRect.html[clEnqueueCopyBufferRect].#

'''

[[enqueue_map_buffer]]
* <<enqueue_params, _ptr_>>, _event_ = *enqueue_map_buffer*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _blocking_>>, <<mapflags, _mapflags_>>, _offset_, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_offset_, _size_: integer, +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueMapBuffer.html[clEnqueueMapBuffer].#

[[enqueue_unmap_buffer]]
* _event_ = *enqueue_unmap_buffer*(<<queue, _queue_>>, <<buffer, _buffer_>>, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#The <<enqueue_params, _ptr_>> lightuserdata must contain a pointer returned by _cl.enqueue_map_buffer(&nbsp;)_. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueUnmapMemObject.html[clEnqueueUnmapMemObject].#

'''

[[enqueue_migrate_mem_objects]]
* _event_ = *enqueue_migrate_mem_objects*(<<queue, _queue_>>, <<migrateflags, _migrateflags_>>, {_memobject_}, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_memobject_: <<buffer, buffer>> | <<image, image>> | <<pipe, pipe>>. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueMigrateMemObjects.html[clEnqueueMigrateMemObjects].#

=== image commands

[[enqueue_read_image]]
* _event_ = *enqueue_read_image*(<<queue, _queue_>>, <<image, _image_>>, <<enqueue_params, _blocking_>>, _origin_, _region_, _rowpitch_, _slicepitch_, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_origin_, _region_: <<enqueue_params, {integer}[3]>>, +
_rowpitch_, _slicepitch_: integer, +
<<enqueue_params, _ptr_>>: lightuserdata. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueReadImage.html[clEnqueueReadImage].#

[[enqueue_write_image]]
* _event_ = *enqueue_write_image*(<<queue, _queue_>>, <<image, _image_>>, <<enqueue_params, _blocking_>>, _origin_, _region_, _inrowpitch_, _inslicepitch_, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_origin_, _region_: <<enqueue_params, {integer}[3]>>, +
_inrowpitch_, _inslicepitch_: integer, +
<<enqueue_params, _ptr_>>: lightuserdata. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueWriteImage.html[clEnqueueWriteImage].#

[[enqueue_fill_image]]
* _event_ = *enqueue_fill_image*(<<queue, _queue_>>, <<image, _image_>>, _fillcolor_,  _origin_, _region_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_fillcolor_: binary string, +
_origin_, _region_: <<enqueue_params, {integer}[3]>>. +
The _fillcolor_ binary string may encode either a _float_, a _float[4]_, a _int[4]_, or a _uint[4]_. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueFillImage.html[clEnqueueFillImage].#

[[enqueue_copy_image]]
* _event_ = *enqueue_copy_image*(<<queue, _queue_>>, <<image, _srcimage_>>, <<image, _dstimage_>>, _srcorigin_, _dstorigin_, _region_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_srcorigin_, _dstorigin_: integer, +
_region_: <<enqueue_params, {integer}[3]>>. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueCopyImage.html[clEnqueueCopyImage].#

[[enqueue_copy_image_to_buffer]]
* _event_ = *enqueue_copy_image_to_buffer*(<<queue, _queue_>>, <<image, _srcimage_>>, <<buffer, _dstbuffer_>>, _srcorigin_, _region_, _dstoffset_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_srcorigin_, _region_: <<enqueue_params, {integer}[3]>>, +
_dstoffset_: integer. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueCopyImageToBuffer.html[clEnqueueCopyImageToBuffer].#

[[enqueue_copy_buffer_to_image]]
* _event_ = *enqueue_copy_buffer_to_image*(<<queue, _queue_>>, <<buffer, _srcbuffer_>>, <<image, _dstimage_>>, _srcoffset_, _dstorigin_, _region_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_srcoffset_: integer. +
_dstorigin_, _region_: <<enqueue_params, {integer}[3]>>, +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueCopyBufferToImage.html[clEnqueueCopyBufferToImage].#

'''

[[enqueue_map_image]]
* <<enqueue_params, _ptr_>>, _rowpitch_, _slicepitch_, _event_ = *enqueue_map_image*(<<queue, _queue_>>, <<image, _image_>>, <<enqueue_params, _blocking_>>, <<mapflags, _mapflags_>>, _origin_, _region_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_origin_, _region_: <<enqueue_params, {integer}[3]>>, +
Return values: +
<<enqueue_params, _ptr_>>: lightuserdata, +
_rowpitch_, _slicepitch_: integer. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueMapImage.html[clEnqueueMapImage].#

[[enqueue_unmap_image]]
* _event_ = *enqueue_unmap_image*(<<queue, _queue_>>, <<image, _image_>>, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#The <<enqueue_params, _ptr_>> lightuserdata must contain a pointer returned by _cl.enqueue_map_image(&nbsp;)_. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueUnmapMemObject.html[clEnqueueUnmapMemObject].#

=== GL objects commands

[[enqueue_acquire_gl_objects]]
* _event_ = *enqueue_acquire_gl_objects*(<<queue, _queue_>>, {<<gl_objects, _buffer_>>|<<gl_objects, _image_>>}, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueAcquireGLObjects.html[clEnqueueAcquireGLObjects].#

[[enqueue_release_gl_objects]]
* _event_ = *enqueue_release_gl_objects*(<<queue, _queue_>>, {<<gl_objects, _buffer_>>|<<gl_objects, _image_>>}, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueReleaseGLObjects.html[clEnqueueReleaseGLObjects].#

=== svm commands

[[enqueue_svm_free]]
* _event_ = *enqueue_svm_free*(<<queue, _queue_>>, {<<svm, _svm_>>}, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMFree.html[clEnqueueSVMFree].#

[[enqueue_svm_memcpy]]
* _event_ = *enqueue_svm_memcpy*(<<queue, _queue_>>, <<enqueue_params, _blocking_>>, <<enqueue_params, _dstptr_>>, <<enqueue_params, _srcptr_>>, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMMemcpy.html[clEnqueueSVMMemcpy].#

[[enqueue_svm_mem_fill]]
* _event_ = *enqueue_svm_mem_fill*(<<queue, _queue_>>, <<enqueue_params, _ptr_>>, _pattern_, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_pattern_: binary string +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMMemFill.html[clEnqueueSVMMemFill].#

'''

[[enqueue_svm_map]]
* _event_ = *enqueue_svm_map*(<<queue, _queue_>>, <<enqueue_params, _blocking_>>, <<mapflags, _mapflags_>>, <<enqueue_params, _ptr_>>, _size_, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMMap.html[clEnqueueSVMMap].#

[[enqueue_svm_unmap]]
* _event_ = *enqueue_svm_unmap*(<<queue, _queue_>>, <<enqueue_params, _ptr_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMUnmap.html[clEnqueueSVMUnmap].#

'''

[[enqueue_svm_migrate_mem]]
* _event_ = *enqueue_svm_migrate_mem*(<<queue, _queue_>>, <<migrateflags, _migrateflags_>>, {<<svm, _svm_>>}, {_offset_}, {_size_}, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueSVMMigrateMem.html[clEnqueueSVMMigrateMem].#


=== kernel commands

[[enqueue_ndrange_kernel]]
* _event_ = *enqueue_ndrange_kernel*(<<queue, _queue_>>, <<kernel, _kernel_>>, _N_, [_globoffset_], _globsize_, [_locsize_], [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#_N_: 1, 2 or 3 (work dimension), +
_globoffset_, _globsize_, _locsize_: <<enqueue_params, {integer}[3]>> (of which only the first _N_ are meaningful), +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueNDRangeKernel.html[clEnqueueNDRangeKernel].#

[[enqueue_task]]
* _event_ = *enqueue_task*(<<queue, _queue_>>, <<kernel, _kernel_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Equivalent to _cl.enqueue_ndrange_kernel(cq, kernel, 1, {0}, {1}, {1}, {we}, ge)_.#

////
[[enqueue_native_kernel]]
* _event_ = *enqueue_native_kernel*(<<queue, _queue_>>, @@, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueNativeKernel.html[clEnqueueNativeKernel].#
////

=== synchronization

[[flush]]
* *flush*(<<queue, _queue_>>) +
[small]#Blocks until all previously enqueued commands have been submitted. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clFlush.html[clFlush].#

[[finish]]
* *finish*(<<queue, _queue_>>) +
[small]#Blocks until all previously enqueued commands have been completed. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clFinish.html[clFinish].#

[[enqueue_marker]]
* _event_ = *enqueue_marker*(<<queue, _queue_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueMarkerWithWaitList.html[clEnqueueMarkerWithWaitList].#

[[enqueue_barrier]]
* _event_ = *enqueue_barrier*(<<queue, _queue_>>, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueBarrierWithWaitList.html[clEnqueueBarrierWithWaitList].#

////

[[enqueue_]]
* _event_ = **(<<queue, _queue_>>, @@, [<<enqueue_params, {_we_}, _ge_>>]) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueue.html[].#

arg3: __, +
__: binary string +

<<buffer, _buffer_>>
<<image, _image_>>
'__': string +
'__': integer +
'__': <<, >> +
////

