
[[event]]
=== event

Event objects can be created in two ways:
with the <<create_user_event, create_user_event>>(&nbsp;) function (*user events*), or
by setting the _ge_ parameter to _true_ when issuing a command with a <<commands, enqueue_xxx>>(&nbsp;)
call (*command events*).

[[create_user_event]]
* _event_ = *create_user_event*(<<context, _context_>>) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clCreateUserEvent.html[clCreateUserEvent].#

[[set_user_event_status]]
* *set_user_event_status*(_event_, _status_) +
[small]#_status_: '_complete_' or negative integer error code. +
(Note: the default status for _event_ is '_submitted_', and this function can be called 
on _event_ only once.) +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clSetUserEventStatus.html[clSetUserEventStatus].#


[[retain_event]]
* *retain_event*(_event_) +
*release_event*(_event_) +
*release_events*({_event_}) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clRetainEvent.html[clRetainEvent] - 
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clReleaseEvent.html[clReleaseEvent].#

[[get_event_info]]
* _value_ = *get_event_info*(_event_, <<eventinfo, _eventinfo_>>) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clGetEventInfo.html[clGetEventInfo].#

[[get_event_profiling_info]]
* _value_ = *get_event_profiling_info*(_event_, <<profilinginfo, _profilinginfo_>>) +
[small]#To use this function, the _command_ identified by _event_ must have been enqueued in a 
command <<queue, _queue_>> created with the '_profiling enabled_' flag set. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clGetEventProfilingInfo.html[clGetEventProfilingInfo].#

[[wait_for_events]]
* *wait_for_events*({_event_}) +
[small]#Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clWaitForEvents.html[clWaitForEvents].#

[[set_event_callback]]
* *set_event_callback*(_event_, _type_) +
_status_ = *check_event_callback*(_event_, _type_) +
[small]#_type_: '_submitted_', '_running_', or '_complete_'. +
_status_: boolean | integer (error code). +
The _set_event_callback(&nbsp;)_ function registers a C callback that, when called by the OpenCL driver,
just stores the execution status information passed to it. The application can then poll the status
information using the _check_event_callback_(&nbsp;) function. +
Rfr: https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clSetEventCallback.html[clSetEventCallback].#

